### ISSUE TITLE
Theme fails to render properly after fixing scss conversion error

### ISSUE THREAD

**Issue by digracesion** [wowthemesnet/affiliates-jekyll-theme#20]
I encountered a `Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/theme.scss': expected "{".` error message after forking the repository and making some changes.

To fix this, I removed the two lines of "----" in the `assets/css/theme.scss` file. The error message disappeared, but then the is not being rendered properly.

My repository can be found here: https://github.com/digracesion/amazon-storefront
The site can be found here: https://digracesion.github.io/amazon-storefront/

Here's a full log of what I got after running `bundle exec jekyll serve --trace --verbose` before encountering the issue:
```
  Logging at level: debug
    Jekyll Version: 4.3.2
Configuration file: /Users/gray/GithubPages/amazon-storefront/_config.yml
  Logging at level: debug
    Jekyll Version: 4.3.2
         Requiring: jekyll-paginate
         Requiring: jekyll-sitemap
         Requiring: jekyll-feed
         Requiring: jekyll-seo-tag
         Requiring: jekyll-archives
            Source: /Users/gray/GithubPages/amazon-storefront
       Destination: /Users/gray/GithubPages/amazon-storefront/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
           Reading: /_layouts/categories.html
           Reading: /_layouts/default.html
           Reading: /_layouts/page.html
           Reading: /_layouts/post.html
       EntryFilter: excluded /node_modules
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
       EntryFilter: excluded /.jekyll-cache
           Reading: assets/css/theme.scss
           Reading: pages/privacy-policy.md
           Reading: pages/contact.html
           Reading: pages/about.md
           Reading: pages/categories.html
           Reading: index.html
           Reading: 404.html
           Reading: _data/menus.yml
        Generating: Jekyll::Archives::Archives finished in 3.9e-05 seconds.
       Jekyll Feed: Generating feed for posts
        Generating: JekyllFeed::Generator finished in 0.001869 seconds.
        Generating: Jekyll::JekyllSitemap finished in 0.00433 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 0.000448 seconds.
         Rendering: 404.html
  Pre-Render Hooks: 404.html
  Rendering Liquid: 404.html
  Rendering Markup: 404.html
Post-Convert Hooks: 404.html
  Rendering Layout: 404.html
         Rendering: pages/about.md
  Pre-Render Hooks: pages/about.md
  Rendering Markup: pages/about.md
Post-Convert Hooks: pages/about.md
  Rendering Layout: pages/about.md
         Rendering: pages/categories.html
  Pre-Render Hooks: pages/categories.html
  Rendering Markup: pages/categories.html
Post-Convert Hooks: pages/categories.html
  Rendering Layout: pages/categories.html
         Rendering: pages/contact.html
  Pre-Render Hooks: pages/contact.html
  Rendering Liquid: pages/contact.html
  Rendering Markup: pages/contact.html
Post-Convert Hooks: pages/contact.html
  Rendering Layout: pages/contact.html
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
Post-Convert Hooks: index.html
  Rendering Layout: index.html
         Rendering: pages/privacy-policy.md
  Pre-Render Hooks: pages/privacy-policy.md
  Rendering Markup: pages/privacy-policy.md
Post-Convert Hooks: pages/privacy-policy.md
  Rendering Layout: pages/privacy-policy.md
         Rendering: assets/css/theme.scss
  Pre-Render Hooks: assets/css/theme.scss
  Rendering Markup: assets/css/theme.scss
Error: Expected identifier.
    ╷
610 │     transition: all.3s;
    │                     ^
    ╵
  /Users/gray/GithubPages/amazon-storefront/assets/css/theme.scss 610:21  root stylesheet 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/theme.scss':
                    Expected identifier.
bundler: failed to load command: jekyll (/Users/gray/.gem/ruby/3.1.3/bin/jekyll)
/Users/gray/.gem/ruby/3.1.3/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:175:in `rescue in convert': Expected identifier. (Jekyll::Converters::Scss::SyntaxError)
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:159:in `convert'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:105:in `block in convert'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `each'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `reduce'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `convert'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:84:in `render_document'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:564:in `block in render_pages'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `each'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `render_pages'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:211:in `render'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from /Users/gray/.gem/ruby/3.1.3/bin/jekyll:25:in `load'
        from /Users/gray/.gem/ruby/3.1.3/bin/jekyll:25:in `<top (required)>'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'
        from /Users/gray/.gem/ruby/3.1.3/bin/bundle:25:in `load'
        from /Users/gray/.gem/ruby/3.1.3/bin/bundle:25:in `<main>'
/Users/gray/.gem/ruby/3.1.3/gems/sass-embedded-1.58.0-x86_64-darwin/lib/sass/embedded/protofier.rb:16:in `from_proto_compile_response': Expected identifier. (Sass::CompileError)
        from /Users/gray/.gem/ruby/3.1.3/gems/sass-embedded-1.58.0-x86_64-darwin/lib/sass/embedded/host.rb:66:in `compile_request'
        from /Users/gray/.gem/ruby/3.1.3/gems/sass-embedded-1.58.0-x86_64-darwin/lib/sass/embedded.rb:216:in `compile_string'
        from /Users/gray/.gem/ruby/3.1.3/gems/sass-embedded-1.58.0-x86_64-darwin/lib/sass/embedded.rb:53:in `compile_string'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:160:in `convert'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:105:in `block in convert'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `each'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `reduce'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:104:in `convert'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:84:in `render_document'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:564:in `block in render_pages'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `each'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:563:in `render_pages'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:211:in `render'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /Users/gray/.gem/ruby/3.1.3/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /Users/gray/.gem/ruby/3.1.3/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from /Users/gray/.gem/ruby/3.1.3/bin/jekyll:25:in `load'
        from /Users/gray/.gem/ruby/3.1.3/bin/jekyll:25:in `<top (required)>'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/gray/.gem/ruby/3.1.3/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'
        from /Users/gray/.gem/ruby/3.1.3/bin/bundle:25:in `load'
        from /Users/gray/.gem/ruby/3.1.3/bin/bundle:25:in `<main>'
```

**Comment by iesedobleac** [comment]
I'm going to help you figure this out, as it has taken me weeks to get it right. The problem you mark about adding a key is the least of it. The real problem is right at the end of the `theme.scss` file, make this simple change:

```scss
.hover-opacity:hover {
    transition: all .3s;
    opacity: .8;
}
```

At first glance you can't see what has changed, as it's something really subtle, but just add a space between all and .3s, and everything will work again.

**Comment by digracesion** [comment]
Sorry took me a while to work on this project again, but it's working now after the fix you recommended. Thanks a bunch!
